# Generated by Django 5.0.1 on 2024-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('preview', models.ImageField(upload_to='games/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publisher', models.CharField(max_length=100)),
                ('release_date', models.DateField(auto_now=True)),
                ('age_rating', models.CharField(blank=True, max_length=5, null=True)),
                ('genre', models.CharField(choices=[('adventure', 'Adventure'), ('strategy', 'Strategy'), ('role_playing', 'Role Playing'), ('puzzle', 'Puzzle'), ('card', 'Card'), ('not_selected', 'Not selected')], default='not_selected', max_length=20)),
            ],
        ),
    ]
