# Generated by Django 5.0.1 on 2024-02-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
